### ISSUE TITLE
Download caching

### ISSUE THREAD

**Issue by TheLortex** [ocamllabs/duniverse#15]
In order to make duniverse practical, a caching mechanism need to be implemented. 
This would ensure that the whole universe is not downloaded on each `duniverse pull`.

Another _simpler_ mechanism that could be a first step towards that would be to not re-download a package that has locally been downloaded in `./duniverse/` vendor directory. That also ensures that a `duniverse pull` won't overwrite local work.

**Comment by Julow** [comment]
If the user have opam installed, we could use its download cache.

For example:
`opam show -f url.checksum ptime` gives `"md5=12fb5e8c3eb1d2e6075ac31ce93f7dd6"`
so the archive is `.opam/download-cache/md5/12/12fb5e8c3eb1d2e6075ac31ce93f7dd6`

**Comment by avsm** [comment]
I like @Jules' idea of using the opam cache for now.  It's kind of hard to know if a local version needs updating or not, since we need to extract the upstream archive and compare it with a recursive diff with the local version.  You can't even just decompress the new archive since that won't delete files from the old archive.

**Comment by TheLortex** [comment]
Two options that we can explore for faster downloads:
* Using a git cache: https://randyfay.com/content/reference-cache-repositories-speed-clones-git-clone-reference
* Using `git clone --depth 1` in order not to download the whole history.

**Comment by avsm** [comment]
merged, but #92 to track a lingering bug
