### ISSUE TITLE
Update and fix duniverse's duniverse

### ISSUE THREAD

**Issue by NathanReb** [ocamllabs/duniverse#78]
As pointed out by @misterda, our CI is currently broken because of what seems to be a misconfigured duniverse.

It also seems that our duniverse contains some old versions of our dependencies that could seemlessly be upgraded to allow compatibility with the latest OCaml release.

See https://github.com/ocamllabs/duniverse/issues/77#issuecomment-591574078 for the initial discussion

**Comment by avsm** [comment]
It's not misconfigured -- it's just that the version of the duniverse committed needs dune <2.3.0 due to dune-configurator changing its protocol.

Or to be more precise, the version of _dune_ vendored in the duniverse needs to match the host binary of dune.  @rgrinberg, perhaps we need more precise versioning here between the dune host binary and the associated dune libraries, as matching them precisely is difficult with a vendored set of libraries.

I'll create an issue later about the broader way to support the range of supported ocaml/dune versions, but for now the immediate issue is fixed by #79's update.

**Comment by avsm** [comment]
Fixed by #79
